<?php

namespace Database\Seeders;

use App\Models\Staff;
use Illuminate\Database\Seeder;

class StaffSeeder extends Seeder
{
    /**
     * Run the database seeds with real staff members from PERSONAL SEPTIEMBRE 2026.xls
     */
    public function run(): void
    {
        $staffMembers = [
            // Bartenders de Barras Oficiales
            [
                'name' => 'KELLY',
                'role' => 'Bartender Principal',
                'assigned_bar' => 'Barra Principal',
                'default_pay' => 100.00,
                'works_friday' => true,
                'works_saturday' => true,
                'works_sunday' => true,
                'friday_pay' => 100.00,
                'saturday_pay' => 110.00,
                'sunday_pay' => 110.00,
            ],
            [
                'name' => 'ARIEL',
                'role' => 'Bartender Subterráneo',
                'assigned_bar' => 'Barra Subterráneo',
                'default_pay' => 100.00,
                'works_friday' => true,
                'works_saturday' => true,
                'works_sunday' => true,
                'friday_pay' => 100.00,
                'saturday_pay' => 110.00,
                'sunday_pay' => 110.00,
            ],

            // Equipo de Seguridad (S)
            [
                'name' => 'ALEX(S)',
                'role' => 'Seguridad',
                'assigned_bar' => 'Seguridad / Puerta',
                'default_pay' => 120.00,
                'works_friday' => true,
                'works_saturday' => true,
                'works_sunday' => true,
                'friday_pay' => 120.00,
                'saturday_pay' => 120.00,
                'sunday_pay' => 120.00,
            ],
            [
                'name' => 'ARIEL(S)',
                'role' => 'Seguridad',
                'assigned_bar' => 'Seguridad',
                'default_pay' => 120.00,
                'works_friday' => true,
                'works_saturday' => true,
                'works_sunday' => true,
                'friday_pay' => 120.00,
                'saturday_pay' => 120.00,
                'sunday_pay' => 120.00,
            ],
            [
                'name' => 'RODRIGO(S)',
                'role' => 'Seguridad',
                'assigned_bar' => 'Seguridad',
                'default_pay' => 120.00,
                'works_friday' => true,
                'works_saturday' => true,
                'works_sunday' => true,
                'friday_pay' => 120.00,
                'saturday_pay' => 130.00,
                'sunday_pay' => 120.00,
            ],
            [
                'name' => 'MAYLEN(S)',
                'role' => 'Seguridad',
                'assigned_bar' => 'Seguridad',
                'default_pay' => 120.00,
                'works_friday' => true,
                'works_saturday' => true,
                'works_sunday' => true,
                'friday_pay' => 120.00,
                'saturday_pay' => 120.00,
                'sunday_pay' => 130.00,
            ],
            [
                'name' => 'LUIS(S)',
                'role' => 'Seguridad',
                'assigned_bar' => 'Seguridad',
                'default_pay' => 120.00,
                'works_friday' => true,
                'works_saturday' => true,
                'works_sunday' => true,
                'friday_pay' => 120.00,
                'saturday_pay' => 120.00,
                'sunday_pay' => 120.00,
            ],
            [
                'name' => 'JAZ(S)',
                'role' => 'Seguridad',
                'assigned_bar' => 'Seguridad',
                'default_pay' => 120.00,
                'works_friday' => true,
                'works_saturday' => true,
                'works_sunday' => false,
                'friday_pay' => 120.00,
                'saturday_pay' => 120.00,
                'sunday_pay' => 120.00,
            ],
            [
                'name' => 'RICO(S)',
                'role' => 'Seguridad',
                'assigned_bar' => 'Seguridad',
                'default_pay' => 120.00,
                'works_friday' => false,
                'works_saturday' => true,
                'works_sunday' => true,
                'friday_pay' => 120.00,
                'saturday_pay' => 130.00,
                'sunday_pay' => 120.00,
            ],
            [
                'name' => 'ENMANUEL(S)',
                'role' => 'Seguridad',
                'assigned_bar' => 'Seguridad',
                'default_pay' => 120.00,
                'works_friday' => false,
                'works_saturday' => true,
                'works_sunday' => true,
                'friday_pay' => 120.00,
                'saturday_pay' => 120.00,
                'sunday_pay' => 120.00,
            ],
            [
                'name' => 'RUBEN(S)',
                'role' => 'Seguridad',
                'assigned_bar' => 'Seguridad',
                'default_pay' => 120.00,
                'works_friday' => false,
                'works_saturday' => true,
                'works_sunday' => true,
                'friday_pay' => 120.00,
                'saturday_pay' => 120.00,
                'sunday_pay' => 120.00,
            ],
            [
                'name' => 'LUCHO(S)',
                'role' => 'Seguridad',
                'assigned_bar' => 'Seguridad Refuerzo Sábado',
                'default_pay' => 120.00,
                'works_friday' => false,
                'works_saturday' => true,
                'works_sunday' => false,
                'friday_pay' => 120.00,
                'saturday_pay' => 120.00,
                'sunday_pay' => 120.00,
            ],

            // Mozos, Meseras y Personal de Atención (Fijos)
            [
                'name' => 'MAURI',
                'role' => 'Staff / Mesero',
                'assigned_bar' => 'Pista / Mozos',
                'default_pay' => 100.00,
                'works_friday' => true,
                'works_saturday' => true,
                'works_sunday' => true,
                'friday_pay' => 100.00,
                'saturday_pay' => 110.00,
                'sunday_pay' => 110.00,
            ],
            [
                'name' => 'DAYSI',
                'role' => 'Staff / Limpieza',
                'assigned_bar' => 'Pista / Mozos',
                'default_pay' => 100.00,
                'works_friday' => true,
                'works_saturday' => true,
                'works_sunday' => true,
                'friday_pay' => 100.00,
                'saturday_pay' => 110.00,
                'sunday_pay' => 110.00,
            ],
            [
                'name' => 'CLAUDIA',
                'role' => 'Staff / Limpieza',
                'assigned_bar' => 'Pista / Mozos',
                'default_pay' => 100.00,
                'works_friday' => true,
                'works_saturday' => true,
                'works_sunday' => true,
                'friday_pay' => 100.00,
                'saturday_pay' => 110.00,
                'sunday_pay' => 110.00,
            ],
            [
                'name' => 'DANIELA',
                'role' => 'Staff / Limpieza',
                'assigned_bar' => 'Pista / Mozos',
                'default_pay' => 100.00,
                'works_friday' => true,
                'works_saturday' => true,
                'works_sunday' => true,
                'friday_pay' => 100.00,
                'saturday_pay' => 110.00,
                'sunday_pay' => 110.00,
            ],
            [
                'name' => 'LILIANA',
                'role' => 'Staff / Limpieza',
                'assigned_bar' => 'Pista / Mozos',
                'default_pay' => 100.00,
                'works_friday' => true,
                'works_saturday' => true,
                'works_sunday' => true,
                'friday_pay' => 100.00,
                'saturday_pay' => 110.00,
                'sunday_pay' => 110.00,
            ],
            [
                'name' => 'CÉSAR',
                'role' => 'Staff / Mesero',
                'assigned_bar' => 'Pista / Mozos',
                'default_pay' => 100.00,
                'works_friday' => true,
                'works_saturday' => true,
                'works_sunday' => true,
                'friday_pay' => 100.00,
                'saturday_pay' => 100.00,
                'sunday_pay' => 110.00,
            ],
            [
                'name' => 'ANAHI',
                'role' => 'Staff / Limpieza',
                'assigned_bar' => 'Pista / Mozos',
                'default_pay' => 100.00,
                'works_friday' => true,
                'works_saturday' => true,
                'works_sunday' => true,
                'friday_pay' => 100.00,
                'saturday_pay' => 110.00,
                'sunday_pay' => 110.00,
            ],
            [
                'name' => 'PEPE',
                'role' => 'Staff / Mesero',
                'assigned_bar' => 'Pista / Mozos',
                'default_pay' => 100.00,
                'works_friday' => true,
                'works_saturday' => true,
                'works_sunday' => true,
                'friday_pay' => 100.00,
                'saturday_pay' => 110.00,
                'sunday_pay' => 110.00,
            ],
            [
                'name' => 'MAURICIO',
                'role' => 'Staff / Mesero',
                'assigned_bar' => 'Pista / Mozos',
                'default_pay' => 100.00,
                'works_friday' => true,
                'works_saturday' => true,
                'works_sunday' => true,
                'friday_pay' => 100.00,
                'saturday_pay' => 100.00,
                'sunday_pay' => 110.00,
            ],
            [
                'name' => 'ANDRÉ',
                'role' => 'Staff / Mesero',
                'assigned_bar' => 'Pista / Mozos',
                'default_pay' => 100.00,
                'works_friday' => false,
                'works_saturday' => true,
                'works_sunday' => true,
                'friday_pay' => 100.00,
                'saturday_pay' => 110.00,
                'sunday_pay' => 110.00,
            ],
            [
                'name' => 'JOSÉ',
                'role' => 'Staff / Mesero',
                'assigned_bar' => 'Pista / Mozos',
                'default_pay' => 100.00,
                'works_friday' => false,
                'works_saturday' => true,
                'works_sunday' => true,
                'friday_pay' => 100.00,
                'saturday_pay' => 110.00,
                'sunday_pay' => 110.00,
            ],
            [
                'name' => 'KAREN',
                'role' => 'Staff / Limpieza',
                'assigned_bar' => 'Pista / Mozos',
                'default_pay' => 100.00,
                'works_friday' => true,
                'works_saturday' => true,
                'works_sunday' => false,
                'friday_pay' => 100.00,
                'saturday_pay' => 100.00,
                'sunday_pay' => 100.00,
            ],

            // Refuerzos Exclusivos de Sábado (Noche Fuerte)
            [
                'name' => 'ALAM',
                'role' => 'Staff / Refuerzo Sábado',
                'assigned_bar' => 'Pista Sábado',
                'default_pay' => 100.00,
                'works_friday' => false,
                'works_saturday' => true,
                'works_sunday' => false,
                'friday_pay' => 100.00,
                'saturday_pay' => 100.00,
                'sunday_pay' => 100.00,
            ],
            [
                'name' => 'ALEJANDRO',
                'role' => 'Staff / Refuerzo Sábado',
                'assigned_bar' => 'Pista Sábado',
                'default_pay' => 100.00,
                'works_friday' => false,
                'works_saturday' => true,
                'works_sunday' => false,
                'friday_pay' => 100.00,
                'saturday_pay' => 100.00,
                'sunday_pay' => 100.00,
            ],
            [
                'name' => 'JHERSON',
                'role' => 'Staff / Refuerzo Sábado',
                'assigned_bar' => 'Pista Sábado',
                'default_pay' => 100.00,
                'works_friday' => false,
                'works_saturday' => true,
                'works_sunday' => false,
                'friday_pay' => 100.00,
                'saturday_pay' => 100.00,
                'sunday_pay' => 100.00,
            ],
            [
                'name' => 'JHOSELIN',
                'role' => 'Staff / Refuerzo Sábado',
                'assigned_bar' => 'Pista Sábado',
                'default_pay' => 100.00,
                'works_friday' => false,
                'works_saturday' => true,
                'works_sunday' => false,
                'friday_pay' => 100.00,
                'saturday_pay' => 100.00,
                'sunday_pay' => 100.00,
            ],
            [
                'name' => 'SAIDA',
                'role' => 'Staff / Refuerzo Sábado',
                'assigned_bar' => 'Pista Sábado',
                'default_pay' => 100.00,
                'works_friday' => false,
                'works_saturday' => true,
                'works_sunday' => false,
                'friday_pay' => 100.00,
                'saturday_pay' => 100.00,
                'sunday_pay' => 100.00,
            ],

            // Refuerzos Domingo
            [
                'name' => 'JULIETA',
                'role' => 'Staff / Domingo',
                'assigned_bar' => 'Pista Domingo',
                'default_pay' => 110.00,
                'works_friday' => false,
                'works_saturday' => false,
                'works_sunday' => true,
                'friday_pay' => 100.00,
                'saturday_pay' => 110.00,
                'sunday_pay' => 110.00,
            ],
            [
                'name' => 'ZAIDA',
                'role' => 'Staff / Domingo',
                'assigned_bar' => 'Pista Domingo',
                'default_pay' => 110.00,
                'works_friday' => false,
                'works_saturday' => false,
                'works_sunday' => true,
                'friday_pay' => 100.00,
                'saturday_pay' => 110.00,
                'sunday_pay' => 110.00,
            ],
        ];

        foreach ($staffMembers as $s) {
            Staff::updateOrCreate(['name' => $s['name']], $s);
        }
    }
}
